/**
 * Generates research/indexes/*.yaml from record frontmatter.
 * Generated files carry a header and must never be edited by hand;
 * CI detects drift via `--check` (ADR-0010).
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const ROOT = join(import.meta.dir, '..')
const check = process.argv.includes('--check')

function frontmatter(text: string): Record<string, string> {
  const out: Record<string, string> = {}
  const m = /^---\n([\s\S]*?)\n---/.exec(text)
  if (!m) return out
  for (const line of m[1].split('\n')) {
    const kv = /^(\w[\w-]*):\s*(.+)$/.exec(line)
    if (kv) out[kv[1]] = kv[2].trim()
  }
  return out
}

async function scan(dir: string): Promise<Record<string, string>[]> {
  let files: string[] = []
  try {
    files = (await readdir(dir)).filter((f) => f.endsWith('.md')).sort()
  } catch {
    return []
  }
  const records: Record<string, string>[] = []
  for (const f of files) {
    const text = await readFile(join(dir, f), 'utf8')
    const fm = frontmatter(text)
    if (Object.keys(fm).length > 0) records.push(fm)
  }
  return records
}

function numericId(a: Record<string, string>): number {
  const m = /\d+/.exec(a.id ?? '')
  return m ? Number(m[0]) : Number.MAX_SAFE_INTEGER
}

async function yamlIndex(
  name: string,
  records: Record<string, string>[],
  fields: string[],
): Promise<string> {
  const lines = [
    '# Autogenerated by research/tools/generate-indexes.ts — do not edit by hand.',
    `${name}:`,
  ]
  for (const r of [...records].sort((a, b) => numericId(a) - numericId(b))) {
    lines.push(`  ${r.id}:`)
    for (const f of fields) {
      if (r[f] !== undefined) lines.push(`    ${f}: ${r[f]}`)
    }
    if (!records.some((x) => x.title !== undefined)) continue
  }
  return `${lines.join('\n')}\n`
}

const adrs = await scan(join(ROOT, 'decisions', 'adr'))
const sources = [
  ...(await scan(join(ROOT, 'sources', 'repositories'))),
  ...(await scan(join(ROOT, 'sources', 'standards'))),
  ...(await scan(join(ROOT, 'sources', 'technologies'))),
]
const experiments = await scan(join(ROOT, 'experiments', 'results'))
const tasks = await scan(join(ROOT, 'tasks', 'backlog'))

const outputs: Array<[string, string]> = [
  ['adrs.yaml', await yamlIndex('adrs', adrs, ['title', 'status', 'date'])],
  [
    'sources.yaml',
    await yamlIndex('sources', sources, ['title', 'kind', 'url', 'accessed', 'license']),
  ],
  ['experiments.yaml', await yamlIndex('experiments', experiments, ['title', 'status', 'date'])],
  ['tasks.yaml', await yamlIndex('tasks', tasks, ['title', 'status', 'priority'])],
]

for (const [name, content] of outputs) {
  const path = join(ROOT, 'indexes', name)
  const existing = await readFile(path, 'utf8').catch(() => undefined)
  if (existing === content) continue
  if (check) {
    console.error(
      `stale generated index: research/indexes/${name} — run "bun run research:indexes"`,
    )
    process.exitCode = 1
  } else {
    await writeFile(path, content)
    console.log(`wrote research/indexes/${name}`)
  }
}
if (!check) console.log('indexes up to date')
